//AUTOGENERATED FILE FROM png2asset
// Conversion args: \MyBg.png -map

#ifndef METASPRITE_MyBg_H
#define METASPRITE_MyBg_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define MyBg_TILE_ORIGIN 0
#define MyBg_TILE_W 8
#define MyBg_TILE_H 8
#define MyBg_WIDTH 160
#define MyBg_HEIGHT 144
#define MyBg_TILE_COUNT 22
#define MyBg_PALETTE_COUNT 1
#define MyBg_COLORS_PER_PALETTE 4
#define MyBg_TOTAL_COLORS 4
#define MyBg_MAP_ATTRIBUTES 0
extern const unsigned char MyBg_map[360];
#define MyBg_map_attributes MyBg_map

BANKREF_EXTERN(MyBg)

extern const palette_color_t MyBg_palettes[4];
extern const uint8_t MyBg_tiles[352];

#endif
