//AUTOGENERATED FILE FROM png2asset
// Conversion args: RaqueteSprite.png -sw 8 -sh 32 -spr8x8

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

BANKREF(RaqueteSprite)

const palette_color_t RaqueteSprite_palettes[4] = {
	RGB8(255,255,255), RGB8(  0,  0,  0), RGB8(  0,  0,  0), RGB8(  0,  0,  0)
	};

const uint8_t RaqueteSprite_tiles[16] = {
	0x0f,0x00,0x0f,0x00,0x0f,0x00,0x0f,0x00,0x0f,0x00,0x0f,0x00,0x0f,0x00,0x0f,0x00
	};

const metasprite_t RaqueteSprite_metasprite0[] = {
	METASPR_ITEM(-16, -4, 0, S_PAL(0)),
	METASPR_ITEM(8, 0, 0, S_PAL(0)),
	METASPR_ITEM(8, 0, 0, S_PAL(0)),
	METASPR_ITEM(8, 0, 0, S_PAL(0)),
	METASPR_TERM
};

const metasprite_t RaqueteSprite_metasprite1[] = {
	METASPR_ITEM(-16, -4, 0, S_PAL(0) | S_FLIPX),
	METASPR_ITEM(8, 0, 0, S_PAL(0) | S_FLIPX),
	METASPR_ITEM(8, 0, 0, S_PAL(0) | S_FLIPX),
	METASPR_ITEM(8, 0, 0, S_PAL(0) | S_FLIPX),
	METASPR_TERM
};

const metasprite_t* const RaqueteSprite_metasprites[2] = {
	RaqueteSprite_metasprite0, RaqueteSprite_metasprite1
};
