//AUTOGENERATED FILE FROM png2asset
// Conversion args: RaqueteSprite.png -sw 8 -sh 32 -spr8x8

#ifndef METASPRITE_RaqueteSprite_H
#define METASPRITE_RaqueteSprite_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define RaqueteSprite_TILE_ORIGIN 0
#define RaqueteSprite_TILE_W 8
#define RaqueteSprite_TILE_H 8
#define RaqueteSprite_WIDTH 8
#define RaqueteSprite_HEIGHT 32
#define RaqueteSprite_TILE_COUNT 1
#define RaqueteSprite_PALETTE_COUNT 1
#define RaqueteSprite_COLORS_PER_PALETTE 4
#define RaqueteSprite_TOTAL_COLORS 4
#define RaqueteSprite_PIVOT_X 4
#define RaqueteSprite_PIVOT_Y 16
#define RaqueteSprite_PIVOT_W 8
#define RaqueteSprite_PIVOT_H 32
extern const metasprite_t* const RaqueteSprite_metasprites[2];

BANKREF_EXTERN(RaqueteSprite)

extern const palette_color_t RaqueteSprite_palettes[4];
extern const uint8_t RaqueteSprite_tiles[16];

#endif
